# Generated by Django 4.1.2 on 2022-11-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epsiodes', models.IntegerField(verbose_name='Episodes')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('ratings', models.CharField(max_length=255, verbose_name='Ratings')),
                ('scores', models.FloatField(verbose_name='Scores')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('popularity', models.IntegerField(verbose_name='Popularity')),
                ('members', models.BigIntegerField(verbose_name='Members')),
                ('favorites', models.BigIntegerField(verbose_name='Favorites')),
                ('title', models.CharField(max_length=255, verbose_name='titles')),
                ('sp', models.CharField(max_length=255, verbose_name='SP')),
                ('genre', models.CharField(max_length=255, verbose_name='Genre')),
                ('studio', models.CharField(max_length=255, verbose_name='Studio')),
            ],
        ),
    ]
