# Generated by Django 4.1.2 on 2022-11-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_anime_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.CharField(max_length=255, verbose_name='Studio'),
        ),
    ]
